services:
  - type: web
    name: rifapp
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false  # Debes configurar esto en el dashboard de Render
      - key: DB_NAME
        value: MICONEXION
      - key: COLLECTION_NAME
        value: Rifa
